"""Update Emotion table

Revision ID: 26f5dced0068
Revises: 3b1aec6dc81a
Create Date: 2022-09-16 06:09:21.885838

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '26f5dced0068'
down_revision = '3b1aec6dc81a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emotion', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emotion', sa.Column('image_url', mysql.VARCHAR(length=1024), nullable=False))
    # ### end Alembic commands ###
