"""Update Parent and Child Tables

Revision ID: 3b1aec6dc81a
Revises: c7f940ae501a
Create Date: 2022-09-16 04:17:57.513340

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3b1aec6dc81a'
down_revision = 'c7f940ae501a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('child', sa.Column('nickname_updated_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('child', 'nicknamed_updated_at')
    op.add_column('parent', sa.Column('nickname_updated_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('parent', 'nicknamed_updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parent', sa.Column('nicknamed_updated_at', mysql.DATETIME(), nullable=False))
    op.drop_column('parent', 'nickname_updated_at')
    op.add_column('child', sa.Column('nicknamed_updated_at', mysql.DATETIME(), nullable=False))
    op.drop_column('child', 'nickname_updated_at')
    # ### end Alembic commands ###
