"""Add Table

Revision ID: 4f1cc9361ac0
Revises: d3f23b88157b
Create Date: 2022-09-16 16:53:34.865539

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4f1cc9361ac0'
down_revision = 'd3f23b88157b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_diary_reply', sa.Column('question_diary_id', sa.Integer(), nullable=False))
    op.drop_constraint('question_diary_reply_ibfk_1', 'question_diary_reply', type_='foreignkey')
    op.create_foreign_key(None, 'question_diary_reply', 'question_diary', ['question_diary_id'], ['id'])
    op.drop_column('question_diary_reply', 'diary_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_diary_reply', sa.Column('diary_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'question_diary_reply', type_='foreignkey')
    op.create_foreign_key('question_diary_reply_ibfk_1', 'question_diary_reply', 'question_diary', ['diary_id'], ['id'])
    op.drop_column('question_diary_reply', 'question_diary_id')
    # ### end Alembic commands ###
