"""Update ParentChild, Child Tables

Revision ID: 671da503e5ce
Revises: 4f1cc9361ac0
Create Date: 2022-09-18 17:44:30.926839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '671da503e5ce'
down_revision = '4f1cc9361ac0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('child', sa.Column('invitation_code', sa.VARCHAR(length=8), nullable=True))
    op.add_column('child', sa.Column('invitation_code_expired_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('parent_child', sa.Column('invitation_code', sa.VARCHAR(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parent_child', 'invitation_code')
    op.drop_column('child', 'invitation_code_expired_date')
    op.drop_column('child', 'invitation_code')
    # ### end Alembic commands ###
