"""Update Activity Table

Revision ID: 9899e91861b5
Revises: b8a2202b7c73
Create Date: 2022-09-16 10:29:54.906091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9899e91861b5'
down_revision = 'b8a2202b7c73'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
