"""Update Activity Table

Revision ID: b8a2202b7c73
Revises: 3dc896cb9543
Create Date: 2022-09-16 10:29:17.320767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8a2202b7c73'
down_revision = '3dc896cb9543'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
